/* Generated By:JavaCC: Do not edit this line. reg2autoTreeConstants.java Version 5.0 */
public interface reg2autoTreeConstants
{
  public int JJTSTART = 0;
  public int JJTEXPRESSION = 1;
  public int JJTPIPEEXPRESSION = 2;
  public int JJTEXPRESSIONTYPE = 3;
  public int JJTPARENTHESISEXP = 4;
  public int JJTRANGEEXP = 5;
  public int JJTRANGE = 6;
  public int JJTQUALIFIER = 7;
  public int JJTCOMPLEXQUALIFIER = 8;
  public int JJTCQT = 9;
  public int JJTCQT2 = 10;
  public int JJTCQT3 = 11;
  public int JJTCQT4 = 12;
  public int JJTCQT5 = 13;
  public int JJTTERMINAL = 14;
  public int JJTT1 = 15;
  public int JJTLETTER = 16;
  public int JJTNUMBER = 17;


  public String[] jjtNodeName = {
    "Start",
    "Expression",
    "PipeExpression",
    "ExpressionType",
    "ParenthesisExp",
    "RangeExp",
    "Range",
    "Qualifier",
    "ComplexQualifier",
    "CQT",
    "CQT2",
    "CQT3",
    "CQT4",
    "CQT5",
    "Terminal",
    "T1",
    "Letter",
    "Number",
  };
}
/* JavaCC - OriginalChecksum=db8042a99e6b8e474b3f6383469880ad (do not edit this line) */
