/* Generated By:JJTree&JavaCC: Do not edit this line. reg2autoConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface reg2autoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int BACKSLASH = 5;
  /** RegularExpression Id. */
  int PERIOD = 6;
  /** RegularExpression Id. */
  int CARAT = 7;
  /** RegularExpression Id. */
  int DOLLAR_SIGN = 8;
  /** RegularExpression Id. */
  int PIPE = 9;
  /** RegularExpression Id. */
  int SQUARE_BRACKET_BEGIN = 10;
  /** RegularExpression Id. */
  int SQUARE_BRACKET_END = 11;
  /** RegularExpression Id. */
  int PARENTHESIS_BEGIN = 12;
  /** RegularExpression Id. */
  int PARENTHESIS_END = 13;
  /** RegularExpression Id. */
  int EXCLAMATION_POINT = 14;
  /** RegularExpression Id. */
  int QUESTION_MARK = 15;
  /** RegularExpression Id. */
  int ASTERISK = 16;
  /** RegularExpression Id. */
  int PLUS = 17;
  /** RegularExpression Id. */
  int BRACE_BEGIN = 18;
  /** RegularExpression Id. */
  int BRACE_END = 19;
  /** RegularExpression Id. */
  int COMMA = 20;
  /** RegularExpression Id. */
  int HYPHEN = 21;
  /** RegularExpression Id. */
  int LETTER = 22;
  /** RegularExpression Id. */
  int NUMBER = 23;
  /** RegularExpression Id. */
  int TERMINATE = 24;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\r\"",
    "\"\\b\"",
    "\"\\\\\"",
    "\".\"",
    "\"^\"",
    "\"$\"",
    "\"|\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\"!\"",
    "\"?\"",
    "\"*\"",
    "\"+\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\"-\"",
    "<LETTER>",
    "<NUMBER>",
    "\"\\n\"",
  };

}
